[package]
name = "fx_downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
# Allows multiple things to be done at once (Asynchronous)
tokio = { version = "1", features = ["full"] }

# Library that sends HTTP request to Massive
reqwest = { version = "0.12}

# Translates JSON data from Masssive into Rust 
serde = { version = "1.0", features = ["derive"] }